name: smart_home_app
description: "A  Smart Home Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0




flutter:


  uses-material-design: true


  assets:
     - assets/svg/
     - assets/png/



  fonts:
     - family: WorkSans
       fonts:
         - asset: assets/fonts/WorkSans-Medium.ttf
         - asset: assets/fonts/WorkSans-Regular.ttf

